#!/bin/bash
# desc: Perform a kill to the application which has a ShutdownHook to perform a graceful shutdown. 

    jpid=`ps -ef | grep java | grep '/@appName@/' | awk '{ print $2 }'`
    if [ -z $jpid ] ; then
        echo "Could not find @appName@ Application running. Exiting ... "
    else
        kill $jpid
    fi